---
# Set credential input source
# Currently only supports AIM

- name: Set a credential input source
  command: >-
            SOURCE_ID=$(awx credential_input_sources list
            --input_field_name "{{ item.1.input_field_name }}"
            --target_credential "{{ item.1.target_credential }}"
            --source_credential "{{ item.1.source_credential }}"
            --conf.host "{{ tower_manage_server }}"
            --conf.username "{{ tower_manage_admin_username }}"
            --conf.password "{{ tower_manage_admin_password }}"
            {{ tower_manage_validate_certs | ternary('', '--conf.insecure') }} | tail -1)
            &&
            awx credential_input_sources delete
            $SOURCE_ID
            --conf.host "{{ tower_manage_server }}"
            --conf.username "{{ tower_manage_admin_username }}"
            --conf.password "{{ tower_manage_admin_password }}"
            {{ tower_manage_validate_certs | ternary('', '--conf.insecure') }}
  loop: "{{ tower_objects.organisations | subelements('credential_input_source', 'skip_missing=True') }}"
  ignore_errors: true

- name: Set a credential input source
  command: >-
            awx credential_input_sources create
            --input_field_name "{{ item.1.input_field_name }}"
            --target_credential "{{ item.1.target_credential }}"
            --source_credential "{{ item.1.source_credential }}"
            --metadata '{"object_query_format": "Exact", "object_query":"Safe={{ item.1.safe }};Object{{ item.1.object }}"}'
            --conf.host "{{ tower_manage_server }}"
            --conf.username "{{ tower_manage_admin_username }}"
            --conf.password "{{ tower_manage_admin_password }}"
            {{ tower_manage_validate_certs | ternary('', '--conf.insecure') }}
  loop: "{{ tower_objects.organisations | subelements('credential_input_source', 'skip_missing=True') }}"
  ignore_errors: true

...
