---

# Create RBAC for a team
- name: " Create RBAC entry"
  awx.awx.tower_role:
    team: "{{ item.1.team }}"
    job_template: "{{ item.1.job_template | default(omit) }}"
    organization: "{{ item.1.organization | default(omit) }}"
    inventory: "{{ item.1.inventory | default(omit) }}"
    workflow: "{{ item.1.workflow | default(omit) }}"
    credential: "{{ item.1.credential | default(omit) }}"
    project: "{{ item.1.project | default(omit) }}"
    role: "{{ item.1.role }}"
    state: "{{ tower_manage_proj_state | default('present') }}"
    tower_host: "{{ tower_manage_server }}"
    tower_username: "{{ tower_manage_admin_username }}"
    tower_password: "{{ tower_manage_admin_password }}"
    validate_certs: "{{ tower_manage_validate_certs }}"
  loop: "{{ tower_objects.organisations | subelements('rbac', 'skip_missing=True') }}"

...
