---
- name: "Add extra credentials"
  command: >-
    tower-cli job_template associate_credential
    --job-template "{{ item.1.job_template }}"
    --credential "{{ item.1.credential }}"
    --tower-host "{{ tower_manage_server }}"
    --tower-username {{ tower_manage_admin_username }}
    --tower-password {{ tower_manage_admin_password }} --insecure
  register: result
  changed_when: false
  loop: "{{ tower_objects.organisations | subelements('job_template_credential', 'skip_missing=True') }}"
...
