---

# Create credential

- name: Create a  credential (tower module)
  tower_credential:
    name: "{{ item.1.name }}"
    description: "{{ item.1.description | default(omit) }}"
    organization: "{{ item.0.name }}"
    state: "{{ tower_manage_proj_state | default('present') }}"
    kind: "{{ item.1.kind }}"
    host: "{{ item.1.host | default(omit) }}"
    username: "{{ item.1.username | default(omit) }}"
    password: "{{ item.1.password | default(omit) }}"
    ssh_key_data: "{{ item.1.ssh_key | default(omit) }}"
    tower_username: "{{ tower_manage_admin_username }}"
    tower_password: "{{ tower_manage_admin_password }}"
    tower_host: "{{ tower_manage_server }}"
    validate_certs: "{{ tower_manage_validate_certs }}"
  when: item.1.inputs is undefined
  loop: "{{ tower_objects.organisations | subelements('credential', 'skip_missing=True') }}"

- name: Create a credential
  command: >-
    tower-cli credential create
    --name "{{ item.1.name }}"
    --description "{{ item.1.description | default('') }}"
    --organization "{{ item.0.name }}"
    --credential-type "{{ item.1.kind }}"
    --inputs "{{ item.1.inputs | to_json }}"
    --tower-host "{{ tower_manage_server }}"
    --tower-username {{ tower_manage_admin_username }}
    --tower-password {{ tower_manage_admin_password }} --insecure
  when: item.1.inputs is defined
  loop: "{{ tower_objects.organisations | subelements('credential', 'skip_missing=True') }}"
...
