---

- name: Generate an OpenSSL private key.
  openssl_privatekey:
    path: tower.key
  delegate_to: localhost

- name: Generate an OpenSSL CSR.
  openssl_csr:
    path: tower.csr
    privatekey_path: tower.key
    common_name: "{{ tower_manage_fqdn }}"
  delegate_to: localhost


- name: Generate a Let's Encrypt Certificate
  openssl_certificate:
    path: tower.cert
    csr_path: tower.csr
    privatekey_path: tower.key
    provider: acme
  delegate_to: localhost

- name:
  copy:
    src: "{{ item }}"
    dest: "/etc/tower/{{ item }}"
  with_items:
    - tower.cert
    - tower.csr
    - tower.key