---

# Configure LDAP
- name: Set the LDAP Server URI
  tower_settings:
    name: "AUTH_LDAP_SERVER_URI"
    value: "{{ tower_manage_ldap_server_uri }}"
    tower_username: "{{ tower_manage_admin_username }}"
    tower_password: "{{ tower_manage_admin_password }}"
    tower_host: "{{ tower_manage_server }}"
    validate_certs: "{{ tower_manage_validate_certs }}"

- name: Set the LDAP Bind DN
  tower_settings:
    name: "AUTH_LDAP_BIND_DN"
    value: "{{ tower_manage_ldap_bind_dn }}"
    tower_username: "{{ tower_manage_admin_username }}"
    tower_password: "{{ tower_manage_admin_password }}"
    tower_host: "{{ tower_manage_server }}"
    validate_certs: "{{ tower_manage_validate_certs }}"

- name: Set the LDAP Bind Password
  tower_settings:
    name: "AUTH_LDAP_BIND_PASSWORD"
    value: "{{ tower_manage_ldap_bind_password }}"
    tower_username: "{{ tower_manage_admin_username }}"
    tower_password: "{{ tower_manage_admin_password }}"
    tower_host: "{{ tower_manage_server }}"
    validate_certs: "{{ tower_manage_validate_certs }}"

- name: Set the LDAP Start TLS
  tower_settings:
    name: "AUTH_LDAP_START_TLS"
    value: "{{ tower_manage_ldap_start_tls }}"
    tower_username: "{{ tower_manage_admin_username }}"
    tower_password: "{{ tower_manage_admin_password }}"
    tower_host: "{{ tower_manage_server }}"
    validate_certs: "{{ tower_manage_validate_certs }}"

- name: Set the LDAP User Search
  tower_settings:
    name: "AUTH_LDAP_USER_SEARCH"
    value: "{{ tower_manage_ldap_user_search | string }}"
    tower_username: "{{ tower_manage_admin_username }}"
    tower_password: "{{ tower_manage_admin_password }}"
    tower_host: "{{ tower_manage_server }}"
    validate_certs: "{{ tower_manage_validate_certs }}"

- name: Set the LDAP User DN Template
  tower_settings:
    name: "AUTH_LDAP_USER_DN_TEMPLATE"
    value: "{{ tower_manage_ldap_user_dn_template }}"
    tower_username: "{{ tower_manage_admin_username }}"
    tower_password: "{{ tower_manage_admin_password }}"
    tower_host: "{{ tower_manage_server }}"
    validate_certs: "{{ tower_manage_validate_certs }}"

- name: Set the LDAP User Attribute Map
  tower_settings:
    name: "AUTH_LDAP_USER_ATTR_MAP"
    value: "{{ tower_manage_ldap_user_attr_map | string }}"
    tower_username: "{{ tower_manage_admin_username }}"
    tower_password: "{{ tower_manage_admin_password }}"
    tower_host: "{{ tower_manage_server }}"
    validate_certs: "{{ tower_manage_validate_certs }}"

- name: Set the LDAP Group Search
  tower_settings:
    name: "AUTH_LDAP_GROUP_SEARCH"
    value: "{{ tower_manage_ldap_group_search | string }}"
    tower_username: "{{ tower_manage_admin_username }}"
    tower_password: "{{ tower_manage_admin_password }}"
    tower_host: "{{ tower_manage_server }}"
    validate_certs: "{{ tower_manage_validate_certs }}"

- name: Set the LDAP Group Type
  tower_settings:
    name: "AUTH_LDAP_GROUP_TYPE"
    value: "{{ tower_manage_ldap_group_type }}"
    tower_username: "{{ tower_manage_admin_username }}"
    tower_password: "{{ tower_manage_admin_password }}"
    tower_host: "{{ tower_manage_server }}"
    validate_certs: "{{ tower_manage_validate_certs }}"

- name: Set the LDAP Group Type Parameters
  tower_settings:
    name: "AUTH_LDAP_GROUP_TYPE_PARAMS"
    value: "{{ tower_manage_ldap_group_type_params | string }}"
    tower_username: "{{ tower_manage_admin_username }}"
    tower_password: "{{ tower_manage_admin_password }}"
    tower_host: "{{ tower_manage_server }}"
    validate_certs: "{{ tower_manage_validate_certs }}"

- name: Set the LDAP Require Group
  tower_settings:
    name: "AUTH_LDAP_REQUIRE_GROUP"
    value: "{{ tower_manage_ldap_require_group }}"
    tower_username: "{{ tower_manage_admin_username }}"
    tower_password: "{{ tower_manage_admin_password }}"
    tower_host: "{{ tower_manage_server }}"
    validate_certs: "{{ tower_manage_validate_certs }}"

- name: Set the LDAP Deny Group
  tower_settings:
    name: "AUTH_LDAP_DENY_GROUP"
    value: "{{ tower_manage_ldap_deny_group }}"
    tower_username: "{{ tower_manage_admin_username }}"
    tower_password: "{{ tower_manage_admin_password }}"
    tower_host: "{{ tower_manage_server }}"
    validate_certs: "{{ tower_manage_validate_certs }}"

- name: Set the LDAP User Flags
  tower_settings:
    name: "AUTH_LDAP_USER_FLAGS_BY_GROUP"
    value: "{{ tower_manage_ldap_user_flags_by_group | string }}"
    tower_username: "{{ tower_manage_admin_username }}"
    tower_password: "{{ tower_manage_admin_password }}"
    tower_host: "{{ tower_manage_server }}"
    validate_certs: "{{ tower_manage_validate_certs }}"

- name: Set the LDAP Organization Map
  tower_settings:
    name: "AUTH_LDAP_ORGANIZATION_MAP"
    value: "{{ tower_manage_ldap_organization_map | string }}"
    tower_username: "{{ tower_manage_admin_username }}"
    tower_password: "{{ tower_manage_admin_password }}"
    tower_host: "{{ tower_manage_server }}"
    validate_certs: "{{ tower_manage_validate_certs }}"

- name: Set the LDAP Team Map
  tower_settings:
    name: "AUTH_LDAP_TEAM_MAP"
    value: "{{ tower_manage_ldap_team_map | string }}"
    tower_username: "{{ tower_manage_admin_username }}"
    tower_password: "{{ tower_manage_admin_password }}"
    tower_host: "{{ tower_manage_server }}"
    validate_certs: "{{ tower_manage_validate_certs }}"

...
