---

# Create Job Temnplates
- name: " Create Job Templates"
  awx.awx.tower_job_template:
    name: "{{ item.1.name }}"
    job_type: "{{ item.1.job_type | default('run') }}"
    playbook: "{{ item.1.playbook }}"
    project: "{{ item.1.project }}"
    inventory: "{{ item.1.inventory }}"
    limit: "{{ item.1.limit | default(omit) }}"
    credentials: "{{ item.1.credentials | default([item.1.credential]) }}"
    state: "{{ tower_manage_proj_state | default('present') }}"
    ask_credential: "{{ item.1.ask_credential | default(omit)  }}"
    ask_extra_vars: "{{ item.1.ask_extra_vars | default(omit)  }}"
    extra_vars: "{{ item.1.extra_vars | default(omit)  }}"
    ask_tags: "{{ item.1.ask_tags | default(omit)  }}"
    ask_skip_tags: "{{ item.1.ask_skip_tags | default(omit)  }}"
    verbosity: "{{ item.1.verbosity | default(omit)  }}"
    become_enabled: "{{ item.1.become_enabled | default(omit)  }}"
    survey_enabled: "{{ item.1.survey_enabled | default(omit)  }}"
    survey_spec: "{{ item.1.survey_spec | default(omit)  }}"
    custom_virtualenv: "{{ item.1.custom_virtualenv | default(omit) }}"
    tower_host: "{{ tower_manage_server }}"
    tower_username: "{{ tower_manage_admin_username }}"
    tower_password: "{{ tower_manage_admin_password }}"
    validate_certs: "{{ tower_manage_validate_certs }}"
  loop: "{{ tower_objects.organisations | subelements('job_templates', 'skip_missing=True') }}"

...
