---

# Create Job Schedule

- name: "add new schedule to {{ item.1.job_template }} job_template"
  shell: >-
            JOB_TEMPLATE_ID=$(awx job_templates get '{{ item.1.job_template }}'
            -f human
            --filter 'id'
            --conf.host {{ tower_manage_server }}
            --conf.username {{ tower_manage_admin_username }}
            --conf.password {{ tower_manage_admin_password }}
            {{ tower_manage_validate_certs | ternary('', '--conf.insecure') }} | tail -1)
            &&
            awx schedules create
            --name '{{ item.1.name | default(item.1.job_template + " schedule") }}'
            --description '{{ item.1.description | default('') }}'
            --unified_job_template $JOB_TEMPLATE_ID
            --rrule "DTSTART:{{ item.1.startdatetime | default(ansible_date_time.iso8601_basic_short) }}Z
            RRULE:FREQ={{ item.1.frequency | upper }};INTERVAL={{ item.1.interval | default('1') }}"
            --extra_data '{{ item.1.extra_data | default(omit) }}'
            --conf.host {{ tower_manage_server }}
            --conf.username {{ tower_manage_admin_username }}
            --conf.password {{ tower_manage_admin_password }}
            {{ tower_manage_validate_certs | ternary('', '--conf.insecure') }}
  loop: "{{ tower_objects.organisations | subelements('job_schedules', 'skip_missing=True') }}"
  when: tower_manage_create_schedule
  changed_when: false
  ignore_errors: true

  - name: "modify schedule to {{ item.1.job_template }} job_template"
  shell: >-
            JOB_TEMPLATE_ID=$(awx job_templates get '{{ item.1.job_template }}'
            -f human
            --filter 'id'
            --conf.host {{ tower_manage_server }}
            --conf.username {{ tower_manage_admin_username }}
            --conf.password {{ tower_manage_admin_password }}
            {{ tower_manage_validate_certs | ternary('', '--conf.insecure') }} | tail -1)
            &&
            awx schedules create
            --description '{{ item.1.description | default('') }}'
            --unified_job_template $JOB_TEMPLATE_ID
            --rrule "DTSTART:{{ item.1.startdatetime | default(ansible_date_time.iso8601_basic_short) }}Z
            RRULE:FREQ={{ item.1.frequency | upper }};INTERVAL={{ item.1.interval | default('1') }}"
            --extra_data '{{ item.1.extra_data | default(omit) }}'
            '{{ item.1.name | default(item.1.job_template + " schedule") }}'
            --conf.host {{ tower_manage_server }}
            --conf.username {{ tower_manage_admin_username }}
            --conf.password {{ tower_manage_admin_password }}
            {{ tower_manage_validate_certs | ternary('', '--conf.insecure') }}
  loop: "{{ tower_objects.organisations | subelements('job_schedules', 'skip_missing=True') }}"
  when: tower_manage_create_schedule
  changed_when: false
  ignore_errors
...
