---

# Create Projects
- name: "Add Tower Project with cache timeout and custom virtualenv  "
  awx.awx.tower_project:
    name: "{{ item.1.name }}"
    description: "{{ item.1.description | default(omit) }}"
    organization: "{{ item.0.name }}"
    scm_url: "{{ item.1.scm_url }}"
    scm_type: "{{ item.1.scm_type }}"
    scm_update_on_launch: "{{ item.1.scm_update_on_launch | default(omit) }}"
    scm_update_cache_timeout: 60
    scm_credential: "{{ item.1.scm_credential | default(omit) }}"
    scm_branch: "{{ item.1.scm_branch | default(tower_manage_proj_branch) }}"
    state: "{{ tower_manage_proj_state | default('present') }}"
    custom_virtualenv: "{{ item.1.custom_virtualenv | default(omit) }}"
    tower_host: "{{ tower_manage_server }}"
    tower_username: "{{ tower_manage_admin_username }}"
    tower_password: "{{ tower_manage_admin_password }}"
    validate_certs: "{{ tower_manage_validate_certs }}"
  loop: "{{ tower_objects.organisations | subelements('projects' , 'skip_missing=True')  }}"

...
