---

- name: Generate an OpenSSL private key.
  openssl_privatekey:
    path: tower.key
  delegate_to: localhost

- name: Generate an OpenSSL CSR.
  openssl_csr:
    path: tower.csr
    privatekey_path: tower.key
    common_name: "{{ tower_manage_fqdn }}"
  delegate_to: localhost

- name: Generate a Let's Encrypt Certificate
  acme_certificate:
    account_key_src: /etc/tower/tower.key
    csr: /etc/tower/tower.csr
    dest: /etc/tower/tower.cert
    acme_directory: https://acme-v02.api.letsencrypt.org/directory
    acme_version: 2
    terms_agreed: true
  register: acme_cert
  notify: "restart nginx"

- name: Verify a Let's Encrypt Certificate
  acme_certificate:
    account_key_src: /etc/tower/tower.key
    csr: /etc/tower/tower.csr
    dest: /etc/tower/tower.cert
    acme_directory: https://acme-v02.api.letsencrypt.org/directory
    acme_version: 2
    terms_agreed: true
    data: "{{ acme_cert }}"