---

# Create credential

- name: Create a  credential (tower module)
  awx.awx.tower_credential:
    name: "{{ item.1.name }}"
    description: "{{ item.1.description | default(omit) }}"
    organization: "{{ item.0.name }}"
    state: "{{ tower_manage_proj_state | default('present') }}"
    credential_type: "{{ item.1.credential_type | default(item.1.kind) }}"
    inputs: "{{ item.1.inputs }}"
    tower_username: "{{ tower_manage_admin_username }}"
    tower_password: "{{ tower_manage_admin_password }}"
    tower_host: "{{ tower_manage_server }}"
    validate_certs: "{{ tower_manage_validate_certs }}"
  loop: "{{ tower_objects.organisations | subelements('credential', 'skip_missing=True') }}"

...
