---
- name: Generate an OpenSSL private key.
  openssl_privatekey:
    path: /etc/tower/tower.key

- name: Generate an OpenSSL CSR.
  openssl_csr:
    path: /etc/tower/tower.csr
    privatekey_path: /etc/tower/tower.key
    common_name: "{{ tower_server }}"

- name: Generate a Let's Encrypt Certificate
  openssl_certificate:
    path: /etc/tower/tower.cert
    csr_path: /etc/tower/tower.csr
    provider: acme
    acme_accountkey_path: /etc/tower/tower.key
    acme_challenge_path: /etc/tower/challenges/ansible.com/